### ISSUE TITLE
Assets with non-baseaddr addresses cannot be sent

### ISSUE THREAD

**Issue by zjavax** [bloxbean/cardano-client-lib#106]
![1650520141(1)](https://user-images.githubusercontent.com/16731548/164383286-c9e4ad2f-be4a-4946-984c-a0485848df29.png)

My asset is at (address: auvp)
utgv is baseaddr, and what is obtained through the mnemonic is baseaddr
How do I get it through the mnemonic (address: auvp)

**Comment by zjavax** [comment]
> @zjavax
> 
> By default base address is generated for index = 0 when you are using Account(Network, mnemonic) constructor.
> 
> I think for the other address, the index=1. You can increase the index value to generate different addresses for the same mnemonic.
> 
> Please try the following constructor Account(Network network, String mnemonic, int index)

it is based on this baseaddr to find utxo, not based on this mnemonic to find all addresses, and then find utxo

Error: Unable to get enough Utxos for address
code：
public class TransferTokenTest extends BaseTest {

    public void transfer() throws ApiException, AddressExcepion, CborSerializationException {

        String senderMnemonic = "kit color frog trick speak employ suit sort bomb goddess jewel primary spoil fade person useless measure manage warfare reduce few scrub beyond era";
        Account sender = new Account(Networks.testnet(), senderMnemonic);

        String receiver2 =  "addr_test1qq4pxvsevncnfd7ppmatyavej7kjcukwxugrnk9rsejufvpfqqgflwz7ahhqezd8mx5hfxmwh2stfagm8uwkxreya6rsqfxnz7";

        PaymentTransaction paymentTransaction =
                PaymentTransaction.builder()
                        .sender(sender)
                        .receiver(receiver2)
                        .amount(BigInteger.valueOf(4001))
                        .unit("57fca08abbaddee36da742a839f7d83a7e1d2419f1507fcbf3916522534245525259")  // Policy ID + Asset Name
                        .build();

        long ttl = blockService.getLastestBlock().getValue().getSlot() + 1000;
        TransactionDetailsParams detailsParams =
                TransactionDetailsParams.builder()
                        .ttl(ttl)
                        .build();

        BigInteger fee = feeCalculationService.calculateFee(paymentTransaction, detailsParams
                , null);

        paymentTransaction.setFee(fee);

        Result<TransactionResult> result = transactionHelperService.transfer(paymentTransaction, detailsParams);

        if (result.isSuccessful())
            System.out.println("Transaction Id: " + result.getValue());
        else
            System.out.println("Transaction failed: " + result);

        System.out.println(transactionHelperService.getUtxoTransactionBuilder());

        waitForTransaction(result);
    }


    public static void main(String[] args) throws AddressExcepion, ApiException, CborSerializationException {
        new TransferTokenTest().transfer();
        System.exit(1);
    }
}

**Comment by zjavax** [comment]
> @zjavax
> 
> By default base address is generated for index = 0 when you are using Account(Network, mnemonic) constructor.
> 
> I think for the other address, the index=1. You can increase the index value to generate different addresses for the same mnemonic.
> 
> Please try the following constructor Account(Network network, String mnemonic, int index)

I have tried this way and it doesn't solve the problem.

**Comment by zjavax** [comment]
The address is an encoding of a hash of a public key. Different address means different public key, means different private key. A transaction such as [Transaction 9f56ebbf115dc4a5d0370117b164800a74033b9e84b4fd0cefdd65cdbf5e7582 - Cardanoscan](https://cardanoscan.io/transaction/9f56ebbf115dc4a5d0370117b164800a74033b9e84b4fd0cefdd65cdbf5e7582), which takes inputs from different addresses has to be signed by multiple private keys for all of the input addresses.

Wallet apps do that automatically. They can derive the private keys by the process described, e.g., in [Address Derivation – Cardano Wallet](https://input-output-hk.github.io/cardano-wallet/concepts/address-derivation#hd-sequential-wallets-%C3%A0-la-bip-44).
It doesn’t matter if the addresses are staked or not (“enterprise”) for this.

If that can be done with this (quite strange) Java API, I don’t know. It seems their transaction builder assumes that there is only one “sender” for each transaction.

In that issue, you mention that the proposed solution with selecting another index in the Account constructor did not work.

Did you choose the index for the address, where the asset resides? It’s the last component of the m/1852’/… derivation path shown to you by Eternl.

According to this, I solve it.

DerivationPath build = DerivationPath.builder()
.purpose(new Segment(1852, true))
.coinType(new Segment(1815, true))
.account(new Segment(0, true))
.role(new Segment(1, false))
.index(new Segment(2, false))
.build();
Not only need to modify (index), but also need to modify (role)
address: m/1852’/1815’/0’/1/2

**Comment by satran004** [comment]
@zjavax, 
 I am glad to know that you have solved the issue.

 It seems that the address is an internal address. That's why you need to change "role" (=1). You can derive any address and corresponding public / private key using DerivationPath and HDKeyGenerator api. It's quite flexible.

Also, for internal address derivation path, there is a helper method DerivationPath.createInternalAddressDerivationPath(index). You may want to directly use that.

Regarding single sender in PaymentTransaction api,  yes the high-level api is very simple but there are limitations.

If you want to have more control during transaction building, you may want to check composable functions. It provides a flexible way of creating transactions.

You can check this example 
https://github.com/bloxbean/cardano-client-examples/blob/main/src/main/java/com/bloxbean/cardano/client/examples/function/TransferTransactionMultiSenderMultiReceiverTest.java

**Comment by zjavax** [comment]
@satran004 
You can derive any address and corresponding public / private key using DerivationPath and HDKeyGenerator api. It's quite flexible.
 =========  HDKeyGenerator   There is an example of this in use, I didn't find it.

TransferTransactionMultiSenderMultiReceiverTest.java
==========   I have learned to use this


I would like to continue to ask a few questions.
address1 utxo: 3ada
address2 utxo: 4ada
I want to send a transaction: 5ada, how do I do it?

**Comment by satran004** [comment]
So with high level api,  you can pass manually selected utxos (through UtxoSelector), so the lib will not try to find utxos automatically. So set all utxos to utxosToInclude. Set account1 in sender field.

Add account2 to additionalWitnessAccounts field. So that transaction will be signed by both account1 and account2.

I think it should work. 

```
PaymentTransaction.builder()
                        .utxosToInclude(utxos)
                        .additionalWitnessAccounts(accounts)
                        .sender(sender)
                        .receiver(receiver)
                        .amount(BigInteger.valueOf(12))
                        .unit("329728f73683fe04364631c27a7912538c116d802416ca1eaf2d7a96736174636f696e")
                        .build();
```

For, functional api, you need to define expected output first and then create inputs from Utxos. There is a "createFromUtxos" method in InputBuilder.  

Let me create examples for both scenarios. I will post sample code here later.

Alternatively, you can just use low level apis like TransactionInput, TransactionOutput directly.
