### ISSUE TITLE
The possibility to rollback code to java-8

### ISSUE THREAD

**Issue by EV6999** [bloxbean/cardano-client-lib#123]
Hello, it seems java-11 is used in the latest version v0.2.0. There are some features related staking that we cannot use in the latest version because java-8 is used in our project.

I open this inquiry to check if it's possible to rollback to java-8.
A compilation target to be java-11 (i.e. JAR/class files will be compiled to java-11) would also be fine, but the code still need to be written in java-8.

Thank you.

Frank

**Comment by satran004** [comment]
@EV6999 Yes, the latest 0.2.0 needs min Java-11.  

It was changed with the following assumptions:

- Java-17 LTS is available since Sept 2021. Java-8 (LTS) **active support** has already been **ended** and only security support is there (which will end on 31st March 2025) https://endoflife.date/java

- Most probably, the Cardano Java apps are new apps using recent Java versions.

Just wondering if it's possible to move your app to Java-11. At least we can then use some new Java features in the lib :)

It would be interesting to see the most used Java version in the community. If Java 8 is still used by most devs for their Cardano apps, we can  plan to rollback to java-8.

**Comment by EV6999** [comment]
Thank you @satran004 for your reply. I think we have to move to Java-11. I will close the ticket.
