### ISSUE TITLE
AddressHelper

### ISSUE THREAD

**Issue by matiwinnetou** [bloxbean/cardano-client-lib#14]
It would be nice to have a utility class that would verify whether a given address provided as a String is valid.

As a bonus such an utility method could return whether address is byron era or shelley era addr.

**Comment by satran004** [comment]
Makes sense to create a helper for that.
 
Though in 0.1.3-beta, there is a method in  Account.toBytes(String address) which returns a byte[] if valid address, otherwise throws exception.

https://github.com/bloxbean/cardano-client-lib/blob/71d929995340bf4988a6600040f44ff19c9bf7de/src/main/java/com/bloxbean/cardano/client/account/Account.java#L185

**Comment by satran004** [comment]
Details : https://github.com/bloxbean/cardano-client-lib/commit/39e9122237e8878e2e2ed0a7133603f316c37533
