### ISSUE TITLE
Bug - NullPointerException for Redeemer Index for minting or staking scripts

### ISSUE THREAD

**Issue by will991** [bloxbean/cardano-client-lib#170]
I am trying to spend a script output while also minting a new token in the same transaction. I understand that a `Redeemer` should have an `index` set that references the Tx script input it corresponds to.

But I don't understand what I should set the index to if it's a `unitRedeemer` for a minting policy that does not have a corresponding input.

Hence, I get a `NullPointerException` in the `Redeemer` class when it tries to execute this line:
```
redeemerArray.add(new UnsignedInteger(this.index));
```

The `UnsignedInteger` constructor calls a `requireNonNull`. The same happens for staking script redeemers or in other words redeemers with the `Reward` tag.

**Comment by satran004** [comment]
>> But I don't understand what I should set the index to if it's a unitRedeemer for a minting policy that does not have a corresponding input.

@will991 
AFAIK, the index in redeemer for a minting script can be set to 0.

I just tried a similar example and it works. 

https://github.com/bloxbean/cardano-client-examples/blob/main/src/test/java/com/bloxbean/cardano/client/example/function/minting/MintTokenAndScriptTxn.java

Fyi, the redeemer index is set in the out-of-box composable function. ``ScriptCallContextProviders.scriptCallContext()``

**Comment by satran004** [comment]
Txn :  https://testnet.cexplorer.io/tx/17aaaafc598c827ec3807cb750b0c86fc71a3f4c4469e6ae4cd000b436a4110b/contract#data

**Comment by will991** [comment]
Thanks for the `ScriptCallContext` reference. I am spending from a script address though via a reference script and `scriptCallContext` seems to add the passed plutus script as witness which is not what I want.

So I am not sure if that's still part of the original problem, but I guess I can just set the index to zero to avoid that issue.
@satran004 perhaps you can direct me to an existing example of how one would go about spending from a script via reference scripts? Thanks!

**Comment by satran004** [comment]
@will991 
>  but I guess I can just set the index to zero to avoid that issue.

Yes for mint redeemer, that should work.

> @satran004 perhaps you can direct me to an existing example of how one would go about spending from a script via reference scripts? Thanks!

In the previous example, I am using reference script. For "GuessSumContract" script, after scriptCallContext call is done, I am removing "sumScript" from witnessset explicitly.

Here's the exact line number 
https://github.com/bloxbean/cardano-client-examples/blob/5075bcc42c05827c8b2a634a12171df5fa59981b/src/test/java/com/bloxbean/cardano/client/example/function/minting/MintTokenAndScriptTxn.java#L194

If you are using composable function, then actually you can do any customization to the transaction object through your own function.

Btw, the plan is to provide another helper method in ScriptCallContextProviders specific to reference script, so that we don't need to manually remove the script.

For more examples of V2 CIPs, you can also check integration-tests here
https://github.com/bloxbean/cardano-client-lib/tree/master/integration-test/src/it/java/com/bloxbean/cardano/client/function

Hope that helps.
