### ISSUE TITLE
Support linux with s390x processor architecture

### ISSUE THREAD

**Issue by avolkov-dev** [bloxbean/cardano-client-lib#18]
Is it possible to compile library to use with [s390x ](https://ru.wikipedia.org/wiki/IBM_System/390) architecture?

**Comment by satran004** [comment]
I have to check. I have no idea if s390x arch is supported through GitHub action.

**Comment by avolkov-dev** [comment]
Looks like it's possible.

https://github.com/marketplace/actions/run-on-architecture

**Comment by satran004** [comment]
@avolkov-dev thanks for the pointer. 

I am not sure if we include additional platform specific libraries in the jar as it may increase the jar size.

Possible solution:-
- Change  cardano-client-lib, so that client application can provide platform specific  binary by providing a path to native lib through system property.
- Additional platform specific native libraries can be  downloaded from GitHub.

**Comment by avolkov-dev** [comment]
I think that would be really cool and flexible approach!

**Comment by satran004** [comment]
@avolkov-dev 
The v0.1.4 of the lib has support for customized path/name for the native lib. 
The build for s390x is not there yet, but you may want to build the native lib manually and try. 

Opotion-1:  Point to native lib in the filesystem

    System.setProperty("jna.library.path", "/home/xyz/");    
    System.setProperty(LibraryUtil.CARDANO_CLIENT_NATIVE_LIB_NAME, "cardano-native-lib");

Option-2 : Bundle native lib in another jar
Make the native library available on your classpath, under the path {OS}-{ARCH}/{LIBRARY}, where {OS}-{ARCH} is JNA's canonical prefix for native libraries (e.g. win32-x86, linux-amd64, or darwin). 
Check details here: - https://github.com/java-native-access/jna/blob/master/www/GettingStarted.md

**Comment by avolkov-dev** [comment]
thanks a lot, will take a look.

**Comment by satran004** [comment]
Next release will be pure Java. So this is no longer required.
