### ISSUE TITLE
re-use policy id

### ISSUE THREAD

**Issue by kang-chen** [bloxbean/cardano-client-lib#185]
Hi, firstly great lib and alternative to PAB.

Been looking through the code and trying to find a way I can keep the same minting policy ID.

You have `createMultiSigScriptAllPolicy` this creates a fresh policy every execution, although would be helpful if we could import a policy or store it offline outside of the application memory.

Is there a way to achieve this with existing methods?

**Comment by satran004** [comment]
@kang-chen Currently PolicyUtil provides some util methods to create commonly used policies. But you can always export the SecretKey and Script object (ScriptAll, ScriptPubKey etc.) to json and store it in database or filesystem or any secure storage. Alternatively, you can also export Policy object if you are creating the policy with PolicyUtil.

Then during minting, you can load the existing policy script and secret key like a regular json to object parsing and use.

Something like this if you are using Jackson library
```
ScriptPubkey scriptPubkey = mapper.readValue(json, ScriptPubkey.class);
```

Once you have the Script file, you can just follow the stand txn building approach.

Here's an example of multisig app where this approach is used. The loaded policy is used in MintingService class in the same package.
https://github.com/bloxbean/bloxbean-playground/blob/master/src/main/java/com/bloxbean/playground/minter/PolicyProvider.java

Here are some more examples : https://github.com/bloxbean/cardano-client-examples/blob/main/src/test/java/com/bloxbean/cardano/client/example/

Hope that helps.

**Comment by kang-chen** [comment]
Hi, thanks for the response.

Confirming if we're using the policy model from bloxbean, will it require a payment signing key to be in there? as per https://github.com/bloxbean/bloxbean-playground/blob/master/src/main/resources/policy.json

I'm trying to achieve something closer to a generic policy with just pub key hash and optionally slot times.

`{
    "type": "all",
    "scripts": [
      {
        "keyHash": "86c4c595371738281d374fa4fa7180b0d3adf56a7eb9ea2d9cbab109",
        "type": "sig"
      },
      {
        "type": "before",
        "slot": 30106442
      }
    ]
}`

Thanks.

**Comment by satran004** [comment]
Great. You figured it out.

You are right, the Policy object is just to keep everything in one object. Just an option. You don't need to keep actual payment keys there.

Payment keys are only required during signing like below. You can provide that in whatever way you like.

Transaction signedTxn = TransactionSigner.INSTANCE.sign(transaction, secretKey);

or, if you are using Composable function api, you can provide account / secret key / policy or directly a pvt key to get a Signer (https://github.com/bloxbean/cardano-client-lib/blob/master/function/src/main/java/com/bloxbean/cardano/client/function/helper/SignerProviders.java#L12)

You can find many examples in integration-test module of main repo or in example repo.

>> might be a dumb question but why is there the additional payment signing key array, assume it's multisig?

Yes, that's for multiple signing keys.. For example: you can have a policy which requires min 2 out of 3 signatures for the transaction to be successful. So the "type" in that case will be "atLeast" instead of sig.
