### ISSUE TITLE
Can't execute ADA payment from wallet with multiple assets

### ISSUE THREAD

**Issue by nemo83** [bloxbean/cardano-client-lib#52]
Hi,

just got this error:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeError { location: Some("Transaction.body.TransactionBody.outputs.TransactionOutputs.TransactionOutput.amount.Value.coin.BigNum"), failure: CBOR(Expected(UnsignedInteger, Map)) }', src/transaction.rs:14:61
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeError { location: Some("Transaction.body.TransactionBody.outputs.TransactionOutputs.TransactionOutput.amount.Value.coin.BigNum"), failure: CBOR(Expected(UnsignedInteger, Tag)) }', src/transaction.rs:14:61
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2021-12-30 11:45:57 ERROR c.b.c.c.b.a.h.TransactionHelperService  Trasaction submission failed
Error Error while processing refund: Result{successful=false, response='{"error":"Bad Request","message":"\"transaction read error RawCborDecodeError [DecoderErrorDeserialiseFailure \\\"Byron Tx\\\" (DeserialiseFailure 0 \\\"end of input\\\"),DecoderErrorDeserialiseFailure \\\"Shelley Tx\\\" (DeserialiseFailure 0 \\\"end of input\\\"),DecoderErrorDeserialiseFailure \\\"Shelley Tx\\\" (DeserialiseFailure 0 \\\"end of input\\\"),DecoderErrorDeserialiseFailure \\\"Shelley Tx\\\" (DeserialiseFailure 0 \\\"end of input\\\"),DecoderErrorDeserialiseFailure \\\"Shelley Tx\\\" (DeserialiseFailure 0 \\\"end of input\\\")]\"","status_code":400}', code=400, value=TransactionResult(signedTxn=[], transactionId=null)}
```

The source address is `addr1q8048ny8g5cdfftt7s23zak0ukpfslfuw930zaehd3z4zpy6g4kz5f5jjy8453xyrld6frmk7vapjcrf6y0a7p8gl6yqh0u3dz`

And I'm trying to send 5 $ada

Any idea what the issue is?

The same type of payment has been working perfectly, the only difference is that recently I've added some Native Assets to the same address of the same wallet.

Thanks,
Gio

**Comment by satran004** [comment]
@nemo83 The error is due to de-serialization failure. There could be various reasons for that. One of the reason could be negative value in the Value field. 

I just noticed that there is only 3.677 ADA available at the above address. So not enough fund to transfer 5 ADA.

Though there are enough fund at other address under the same account.
"addr1qx4juqqfp8lrp37z37fh3lt3vtu0cj2ayvze5alu94wsg0u6g4kz5f5jjy8453xyrld6frmk7vapjcrf6y0a7p8gl6yqkm5vcd"

As you know, unlike wallets, the lib currently fetches utxos at  only single address  (sender).  To get wallet like behavior and to scan all addresses under an account, we need an another UtxoStrategy impl.. It's still in pipeline.

Can you please confirm if my observation is correct?

**Comment by nemo83** [comment]
OMG I'm so sorry1!!

You're totally right, I've been fooled by the total on yoroi and I knew about the addresses and utxos. But I must have done a manual payment from yoroi and screwed things up.

Sorry for having wasted your time and thanks again for the great library!
