### ISSUE TITLE
Excuse me, what's wrong with this error, after I transfer several transactions in a row, it keeps reporting this error

### ISSUE THREAD

**Issue by chaim-g** [bloxbean/cardano-client-lib#71]
Result{successful=false, response='{"error":"Bad Request","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 0 (fromList [])) (Value 9000000 (fromList []))))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = SafeHash \\\"0f30fd03f3c83b650f63d0b765ea8874772d112c8dbf59a801bb4bb9e5f91531\\\"}) 0]))))])\"","status_code":400}', code=400, value=null}

**Comment by 3461610003** [comment]
I also encountered similar problems. I hope you can reply as soon as possible

**Comment by satran004** [comment]
@chaim-g The error "ValueNotConservedUTxO" is thrown when the total input utxo value doesn't match the total output value + fee.

You can enable DEBUG mode and check values in the final transaction output. Are you using high-level api like PaymentTransaction ?

Can you please check if the sender address has utxos with enough ada ?

One possible reason:

- The address (at index=0) doesn't have enough ada , but the other addresses (at different index) have enough fund.
This may happen when you use the same account from wallet like Yoroi, Daedalus. During a transfer transaction, the change amount is usually returned to a different unused address by these wallets.

This library just checks utxos at the given sender address (most of the time address at index=0). 
It doesn't scan all the addresses under an account like a wallet app does. 

Btw, for better control, you can use low level transaction api instead of high-level apis.

**Comment by chaim-g** [comment]
I think there is something wrong with this node. I was also unable to transfer after a few tests.
